services:
  - type: web
    name: infinite-soft-tech02
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: cd infinity && gunicorn infinity.wsgi:application --bind 0.0.0.0:${PORT:-10000}
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: infinity.settings
      - key: PYTHONUNBUFFERED
        value: '1'
