# Generated by Django 6.0.3 on 2026-03-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('service', models.CharField(choices=[('Mobile Development', 'Mobile Development'), ('App Development', 'App Development'), ('QA Services', 'QA Services'), ('Requirement Analysis', 'Requirement Analysis'), ('Digital Marketing', 'Digital Marketing'), ('Support & Maintenance', 'Support & Maintenance'), ('Business Analysis', 'Business Analysis')], max_length=50)),
                ('budget', models.CharField(choices=[('Below $500', 'Below $500'), ('$1K to $10K', '$1K to $10K'), ('$10K to $50K', '$10K to $50K'), ('Above $50K', 'Above $50K')], max_length=50)),
                ('project_type', models.CharField(choices=[('New Project', 'New Project'), ('Existing Project', 'Existing Project'), ('Support & Maintenance', 'Support & Maintenance')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(choices=[('BCA', 'BCA'), ('BE/B.Tech', 'BE/B.Tech'), ('BSC.IT', 'BSC.IT'), ('Diploma CE/IT', 'Diploma CE/IT'), ('MCA', 'MCA'), ('MSC.IT', 'MSC.IT')], max_length=50)),
                ('current_city', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
