# Generated by Django 6.0.3 on 2026-03-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInquiry',
        ),
        migrations.DeleteModel(
            name='InternshipApplication',
        ),
    ]
