# Generated by Django 6.0.3 on 2026-05-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("infapp", "0002_delete_contactinquiry_delete_internshipapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("short_description", models.CharField(blank=True, max_length=500)),
                (
                    "image",
                    models.CharField(help_text="Path to image file", max_length=255),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("software", "Software"),
                            ("hrms", "HRMS"),
                            ("ecommerce", "E-Commerce"),
                            ("retail", "Retail"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "features",
                    models.TextField(help_text="Comma-separated list of features"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("short_description", models.CharField(blank=True, max_length=500)),
                (
                    "image",
                    models.CharField(help_text="Path to image file", max_length=255),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("web", "Web Development"),
                            ("mobile", "Mobile Apps"),
                            ("ai", "AI Solutions"),
                            ("software", "Software"),
                        ],
                        max_length=50,
                    ),
                ),
                ("client", models.CharField(blank=True, max_length=255)),
                (
                    "technologies",
                    models.CharField(
                        blank=True, help_text="Comma-separated list", max_length=500
                    ),
                ),
                ("date_completed", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("short_description", models.CharField(blank=True, max_length=500)),
                (
                    "image",
                    models.CharField(
                        blank=True, help_text="Path to image file", max_length=255
                    ),
                ),
                (
                    "features",
                    models.TextField(help_text="Comma-separated list of features"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon class name", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("founder", "Founder"),
                            ("developer", "Developer"),
                            ("designer", "Designer"),
                            ("manager", "Manager"),
                            ("specialist", "Specialist"),
                        ],
                        max_length=50,
                    ),
                ),
                ("bio", models.TextField()),
                ("short_bio", models.CharField(blank=True, max_length=300)),
                (
                    "image",
                    models.CharField(help_text="Path to image file", max_length=255),
                ),
                (
                    "expertise",
                    models.CharField(
                        blank=True, help_text="Comma-separated list", max_length=500
                    ),
                ),
                (
                    "social_links",
                    models.CharField(
                        blank=True,
                        help_text="JSON format for social links",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
