from django.urls import path

from infapp import views

urlpatterns = [
    path("", views.home, name="home"),
    path("404/", views.page_404, name="page_404"),
    path("about/", views.about, name="about"),
    path("blog-grid-2/", views.blog_grid_2, name="blog_grid_2"),
    path("contact/", views.contact, name="contact"),
    path("faq/", views.faq, name="faq"),
    path("gallery-filter/", views.gallery_filter, name="gallery_filter"),
    path("industries-details/", views.industries_details, name="industries_details"),
    path("industries/", views.industries, name="industries"),
    path("portfolio/", views.portfolio, name="portfolio"),
    path("product-details/", views.product_details, name="product_details"),
    path("product/", views.product, name="product"),
    path("project-details/", views.project_details, name="project_details"),
    path("projects/", views.projects, name="projects"),
    path("service-details/", views.service_details, name="service_details"),
    path("services-2/", views.services_2, name="services_2"),
    path("services-carousel-3/", views.services_carousel_3, name="services_carousel_3"),
    path("services/", views.services, name="services"),
    path("team-details/", views.team_details, name="team_details"),
    path("team/", views.team, name="team"),
    path("technology-android/", views.technology_android, name="technology_android"),
    path("technology-angular/", views.technology_angular, name="technology_angular"),
    path("technology-appium/", views.technology_appium, name="technology_appium"),
    path("technology-aws/", views.technology_aws, name="technology_aws"),
    path("technology-azure/", views.technology_azure, name="technology_azure"),
    path("technology-backend/", views.technology_backend, name="technology_backend"),
    path("technology-cloud-devops/", views.technology_cloud_devops, name="technology_cloud_devops"),
    path("technology-database/", views.technology_database, name="technology_database"),
    path("technology-details/", views.technology_details, name="technology_details"),
    path("technology-dotnet/", views.technology_dotnet, name="technology_dotnet"),
    path("technology-flutter/", views.technology_flutter, name="technology_flutter"),
    path("technology-frontend/", views.technology_frontend, name="technology_frontend"),
    path("technology-gcp/", views.technology_gcp, name="technology_gcp"),
    path("technology-ios/", views.technology_ios, name="technology_ios"),
    path("technology-javascript/", views.technology_javascript, name="technology_javascript"),
    path("technology-magento/", views.technology_magento, name="technology_magento"),
    path("technology-mobile/", views.technology_mobile, name="technology_mobile"),
    path("technology-mongodb/", views.technology_mongodb, name="technology_mongodb"),
    path("technology-mysql/", views.technology_mysql, name="technology_mysql"),
    path("technology-nodejs/", views.technology_nodejs, name="technology_nodejs"),
    path("technology-oracle/", views.technology_oracle, name="technology_oracle"),
    path("technology-other/", views.technology_other, name="technology_other"),
    path("technology-php-laravel/", views.technology_php_laravel, name="technology_php_laravel"),
    path("technology-postgresql/", views.technology_postgresql, name="technology_postgresql"),
    path("technology-postman/", views.technology_postman, name="technology_postman"),
    path("technology-python-django/", views.technology_python_django, name="technology_python_django"),
    path("technology-react-native/", views.technology_react_native, name="technology_react_native"),
    path("technology-react/", views.technology_react, name="technology_react"),
    path("technology-selenium/", views.technology_selenium, name="technology_selenium"),
    path("technology-shopify/", views.technology_shopify, name="technology_shopify"),
    path("technology-spring-boot/", views.technology_spring_boot, name="technology_spring_boot"),
    path("technology-testing/", views.technology_testing, name="technology_testing"),
    path("technology-themeforest/", views.technology_themeforest, name="technology_themeforest"),
    path("technology-xamarin/", views.technology_xamarin, name="technology_xamarin"),
    path("technology/", views.technology, name="technology"),
    path("testimonials/", views.testimonials, name="testimonials"),
]

